"""add scan_status and status_created indexes

Revision ID: fb6789ca310d
Revises: c4a6e7f0b9d1
Create Date: 2026-03-16 21:55:11.694822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6789ca310d'
down_revision: Union[str, Sequence[str], None] = 'c4a6e7f0b9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_scan_status', 'scan_results', ['scan_status'], unique=False)
    op.create_index('idx_status_created', 'scan_results', ['scan_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_created', table_name='scan_results')
    op.drop_index('idx_scan_status', table_name='scan_results')
    op.alter_column('scan_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
